using System;

namespace FF.Rando.Companion.Games.FreeEnterprise.GaleswiftFork;
internal class Descriptors(IFlags? flags) : Games.FreeEnterprise.Descriptors
{
    private readonly IFlags? _flags = flags;

    public string GetRewardSlotName(RewardSlot slot)
        => slot switch
        {
            RewardSlot.StartingCharacter => "Starting character 1",
            RewardSlot.StartingPartnerCharacter => "Starting character 2",
            RewardSlot.MistCharacter => "Mist/Package character",
            RewardSlot.WateryPassCharacter => "Watery Pass character",
            RewardSlot.DamcyanCharacter => "Damcyan character",
            RewardSlot.KaipoCharacter => "Kaipo/SandRuby character",
            RewardSlot.HobsCharacter => "Mt. Hobs character",
            RewardSlot.MysidiaCharacter1 => "Mysidia character 1",
            RewardSlot.MysidiaCharacter2 => "Mysidia character 2",
            RewardSlot.OrdealsCharacter => "Mt. Ordeals character",
            RewardSlot.BaronInnCharacter => "Baron Inn character",
            RewardSlot.BaronCastleCharacter => "Baron Castle character",
            RewardSlot.ZotCharacter1 => "Zot character 1",
            RewardSlot.ZotCharacter2 => "Zot character 2",
            RewardSlot.DwarfCastleCharacter => "Dwarf Castle character",
            RewardSlot.CaveEblanCharacter => "Cave Eblan character",
            RewardSlot.LunarPalaceCharacter => "Lunar Palace character",
            RewardSlot.GiantCharacter => "Giant of Bab-il character",
            RewardSlot.StartingItem => "Starting item",
            RewardSlot.AntlionItem => "Antlion Nest item",
            RewardSlot.FabulItem => "Defend Fabul reward item",
            RewardSlot.OrdealsItem => "Mt. Ordeals item",
            RewardSlot.BaronInnItem => "Baron Inn item",
            RewardSlot.BaronCastleItem => "Baron Castle item",
            RewardSlot.ToroiaHospitalItem when _flags?.KNoFreeMode == KNoFreeMode.DwarfCastle => "Cid/Dwarf Hospital item",
            RewardSlot.ToroiaHospitalItem => "Edward/Toroia item",
            RewardSlot.MagnesItem => "Cave Magnes item",
            RewardSlot.ZotItem => "Zot item",
            RewardSlot.BabilBossItem => "Lower Bab-il item (Tower Key slot)",
            RewardSlot.CannonItem => "Super Cannon destruction item",
            RewardSlot.LucaItem => "Dwarf Castle/Luca item",
            RewardSlot.SealedCaveItem => "Sealed Cave item",
            RewardSlot.FeymarchItem => "Town of Monsters chest item",
            RewardSlot.RatTradeItem => "Rat Tail trade item",
            RewardSlot.FoundYangItem => "Found Yang item (Pan slot)",
            RewardSlot.PanTradeItem => "Pan trade item (Spoon slot)",
            RewardSlot.FeymarchQueenItem => "Town of Monsters queen item (Asura slot)",
            RewardSlot.FeymarchKingItem => "Town of Monsters king item (Levia slot)",
            RewardSlot.BaronThroneItem => "Baron Basement item (Odin slot)",
            RewardSlot.SylphItem => "Wake Yang item (Sylph slot)",
            RewardSlot.BahamutItem => "Cave Bahamut item",
            RewardSlot.LunarBoss1Item => "Lunar Subterrane altar 1 (Murasame slot)",
            RewardSlot.LunarBoss2Item => "Lunar Subterrane altar 2 (Crystal Sword slot)",
            RewardSlot.LunarBoss3Item => "Lunar Subterrane altar 3 (White Spear slot)",
            RewardSlot.LunarBoss4Item1 => "Lunar Subterrane pillar chest 1 (Ribbon slot)",
            RewardSlot.LunarBoss4Item2 => "Lunar Subterrane pillar chest 2 (Ribbon slot)",
            RewardSlot.LunarBoss5Item => "Lunar Subterrane altar 4 (Masamune slot)",
            RewardSlot.ZotChest => "Tower of Zot MIAB",
            RewardSlot.EblanChest1 => "Eblan Castle MIAB",
            RewardSlot.EblanChest2 => "Eblan Castle MIAB",
            RewardSlot.EblanChest3 => "Eblan Castle MIAB",
            RewardSlot.LowerBabilChest1 => "Lower Bab-il MIAB",
            RewardSlot.LowerBabilChest2 => "Lower Bab-il MIAB",
            RewardSlot.LowerBabilChest3 => "Lower Bab-il MIAB",
            RewardSlot.LowerBabilChest4 => "Lower Bab-il MIAB",
            RewardSlot.CaveEblanChest => "Cave Eblan MIAB",
            RewardSlot.UpperBabilChest => "Upper Bab-il MIAB",
            RewardSlot.CaveOfSummonsChest => "Cave of Summons MIAB",
            RewardSlot.SylphCaveChest1 => "Sylph Cave MIAB",
            RewardSlot.SylphCaveChest2 => "Sylph Cave MIAB",
            RewardSlot.SylphCaveChest3 => "Sylph Cave MIAB",
            RewardSlot.SylphCaveChest4 => "Sylph Cave MIAB",
            RewardSlot.SylphCaveChest5 => "Sylph Cave MIAB",
            RewardSlot.SylphCaveChest6 => "Sylph Cave MIAB",
            RewardSlot.SylphCaveChest7 => "Sylph Cave MIAB",
            RewardSlot.GiantChest => "Giant of Bab-il MIAB",
            RewardSlot.LunarPathChest => "Lunar Path MIAB",
            RewardSlot.LunarCoreChest1 => "Lunar Subterrane MIAB",
            RewardSlot.LunarCoreChest2 => "Lunar Subterrane MIAB",
            RewardSlot.LunarCoreChest3 => "Lunar Subterrane MIAB",
            RewardSlot.LunarCoreChest4 => "Lunar Subterrane MIAB",
            RewardSlot.LunarCoreChest5 => "Lunar Subterrane MIAB",
            RewardSlot.LunarCoreChest6 => "Lunar Subterrane MIAB",
            RewardSlot.LunarCoreChest7 => "Lunar Subterrane MIAB",
            RewardSlot.LunarCoreChest8 => "Lunar Subterrane MIAB",
            RewardSlot.LunarCoreChest9 => "Lunar Subterrane MIAB",
            RewardSlot.RydiasMomItem when _flags?.KNoFreeMode == KNoFreeMode.Package => "Package/Rydia's Mom item",
            RewardSlot.RydiasMomItem => "D.Mist/Rydia's Mom item",
            RewardSlot.FallenGolbezItem => "Fallen Golbez item",
            RewardSlot.ForgeItem => "Kokkol forged item",
            RewardSlot.PinkTradeItem => "Pink Tail trade item",
            RewardSlot.FixedCrystal => "Objective completion",
            RewardSlot.GatedObjective => "Gated requirements completion",
            RewardSlot.DwarfHospitalItem => "Cid/Dwarf Hospital item",
            _ => $"UNKNOWN ({slot:x2})"
        };
}
