using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FF.Rando.Companion.Games.JetsOfTime;
internal enum KeyItemType : byte
{
    Magic,

    [Description("Melichor")]
    Masamune,

    [Description("Validation Cat")]
    ValidationCat,

    Pendant = 0xD6,

    [Description("Gate Key")]
    GateKey = 0xD7,

    [Description("Bent Hilt")]
    BentHilt = 0x50,

    [Description("Bent Sword")]
    BentSword = 0x51,

    [Description("Hero's Medal")]
    HerosMedal = 0xB3,

    [Description("Dream Stone")]
    Dreamstone = 0xDC,

    [Description("Robo's Ribbon")]
    RobosRibbon = 0xB8,

    [Description("Prisim Shard")]
    PrismShard = 0xD8,

    Jerky = 0xDB,

    [Description("Sun Stone")]
    SunStone = 0xDE,

    [Description("Moon Stone")]
    MoonStone = 0xDF,

    Clone = 0xE2,

    [Description("Chrono Trigger")]
    ChronoTrigger = 0xD9,

    [Description("Toma's Pop")]
    TomasPop = 0xE3,

    [Description("Masamune")]
    GrandLeon = 0x42,
    RubyKnife = 0xE0,

    [Description("Jets of Time")]
    JetsOfTime = 0xE9,
}

internal enum CharacterType
{
    Chrono, Marle, Lucca, Robo, Frog, Ayla, Magus
}

internal enum PortraitType
{
    Chrono, Marle, Lucca, Robo, Frog, Ayla, Magus, Epoch
}

internal enum BossType
{
    Yakra,
    [Description("Yakra XIII")]
    YakraXIII,
    [Description("Dragon Tank")]
    DragonTank, 
    Guardian,
    [Description("R-Series")]
    RSeries, 
    Heckran,
    Zombor, 
    Retinite,
    [Description("Masa & Mune")]
    MasaAndMune, 
    Nizbel,
    Magus,
    [Description("Black Tyrano")]
    BlackTyrano,
    [Description("Rust Tyrano")]
    RustTyrano,
    [Description("Giga Gaia")]
    GigaGaia,
    [Description("Mother Brain")]
    MotherBrain,
    [Description("Son of Sun")]
    SunOfTheSun, 
    Zeal,
    Golem
}

internal enum NPCType
{
    Melchior = 0x00,
    King_Guardia_XXXIII_1000AD = 0x01,
    Johnny = 0x02,
    Queen_Leene = 0x03,
    Tata = 0x04,
    Toma = 0x05,
    Kino = 0x06,
    Chancellor_Green_1000AD = 0x07,
    Dactyl = 0x08,
    Schala = 0x09,
    Janus = 0x0A,
    Chancellor_Brown_600AD = 0x0B,
    Belthasar = 0x0C,
    Middle_Ages_or_Present_Age_villager_Woman = 0x0D,
    Middle_Ages_or_Present_Age_villager_Young_man = 0x0E,
    Middle_Ages_or_Present_Age_villager_Young_woman = 0x0F,
    Middle_Ages_or_Present_Age_villager_Soldier = 0x10,
    Middle_Ages_or_Present_Age_villager_Old_man = 0x11,
    Middle_Ages_or_Present_Age_villager_Old_woman = 0x12,
    Middle_Ages_or_Present_Age_villager_Little_boy = 0x13,
    Middle_Ages_or_Present_Age_villager_Little_girl = 0x14,
    Middle_Ages_or_Present_Age_villager_Waitress = 0x15,
    Middle_Ages_or_Present_Age_villager_Shopkeeper = 0x16,
    Nun = 0x17,
    Knight_Captain_600AD = 0x18,
    Middle_Ages_or_Present_Age_villager_man = 0x19,
    Dome_survivor_man = 0x1A,
    Dome_survivor_woman = 0x1B,
    Doan = 0x1C,
    Dome_survivor_little_girl = 0x1D,
    Prehistoric_villager_man_with_club = 0x1E,
    Prehistoric_villager_woman_in_green_dress = 0x1F,
    Prehistoric_villager_little_girl = 0x20,
    Prehistoric_villager_old_man = 0x21,
    Zeal_citizen_man = 0x22,
    Zeal_citizen_woman = 0x23,
    Zeal_citizen_researcher_with_glasses = 0x24,
    Cronos_mom = 0x25,
    Middle_Ages_or_Present_Age_villager_little_girl_with_purple_hair = 0x26,
    //Middle_Ages_or_Present_Age_villager_man = 0x27,
    Middle_Ages_or_Present_Age_villager_woman_with_purple_hair = 0x28,
    Middle_Ages_or_Present_Age_villager_young_man = 0x29,
    Middle_Ages_or_Present_Age_villager_young_woman = 0x2A,
    Middle_Ages_or_Present_Age_villager_soldier = 0x2B,
    Middle_Ages_or_Present_Age_villager_old_man = 0x2C,
    Middle_Ages_or_Present_Age_villager_old_woman = 0x2D,
    Middle_Ages_or_Present_Age_villager_little_boy = 0x2E,
    Middle_Ages_or_Present_Age_villager_little_girl = 0x2F,
    Middle_Ages_or_Present_Age_villager_waitress_with_purple_hair = 0x30,
    Middle_Ages_or_Present_Age_villager_shopkeeper = 0x31,
    //Nun = 0x32,
    Guardia_knight_600AD = 0x33,
    //Middle_Ages_or_Present_Age_villager_man = 0x34,
    Cyrus = 0x35,
    Young_Glenn = 0x36,
    King_Guardia_XXI_600AD = 0x37,
    Strength_Test_Machine_part_Millennial_Fair = 0x38,
    Middle_Ages_or_Present_Age_villager_old_man_2C_dupe_UNUSED = 0x39,
    //Zeal_citizen_researcher_with_glasses = 0x3A,
    Cat = 0x3B,
    False_prophet_Magus = 0x3C,
    Melchior_in_gray_robe_UNUSED = 0x3D,
    Prehistoric_villager_man_carrying_club_with_purple_hair = 0x3E,
    Prehistoric_villager_woman_with_purple_hair = 0x3F,
    Prehistoric_villager_little_girl_with_purple_hair = 0x40,
    Algetty_earthbound_one_man = 0x41,
    Algetty_earthbound_one_woman = 0x42,
    Algetty_earthbound_one_old_man = 0x43,
    Algetty_earthbound_one_child = 0x44,
    Princess_Nadia = 0x45,
    Guardia_Castle_chef = 0x46,
    Trial_judge = 0x47,
    Gaspar = 0x48,
    Fiona = 0x49,
    Queen_Zeal = 0x4A,
    Guard_enemy = 0x4B,
    Reptite = 0x4C,
    Kilwala = 0x4D,
    Blue_imp = 0x4E,
    //Middle_Ages_or_Present_Age_villager_man = 0x4F,
    Middle_Ages_or_Present_Age_villager_woman = 0x50,
    GI_Jogger = 0x51,
    Millennial_Fair_visitor_old_man = 0x52,
    Millennial_Fair_visitor_woman = 0x53,
    Millennial_Fair_visitor_little_boy = 0x54,
    Millennial_Fair_visitor_little_girl = 0x55,
    Lightning_bolt = 0x56,
    Opened_time_portal_upper_half = 0x57,
    Opened_time_portal_lower_half = 0x58,
    Millennial_Fair_shopkeeper = 0x59,
    Guillotine_blade = 0x5A,
    Guillotine_chain = 0x5B,
    Conveyor_machine = 0x5C,
    Tombstone = 0x5D,
    Giant_soup_bowl = 0x5E,
    Magus_statue = 0x5F,
    Dreamstone = 0x60,
    Gate_Key = 0x61,
    Soda_can = 0x62,
    Pendant = 0x63,
    Poyozo_doll = 0x64,
    Pink_lunch_bag = 0x65,
    UNUSED = 0x66,
    Red_knife = 0x67,
    Broken_Masamune_blade = 0x68,
    Slice_of_cake = 0x69,
    Trash_can_on_its_side = 0x6A,
    Piece_of_cheese = 0x6B,
    Barrel = 0x6C,
    //UNUSED = 0x6D,
    Dead_sunstone = 0x6E,
    Metal_mug = 0x6F,
    Blue_star = 0x70,
    Giant_blue_star = 0x71,
    Red_flame = 0x72,
    Giant_red_flame = 0x73,
    Explosion_ball = 0x74,
    Giant_explosion_ball = 0x75,
    Smoke_trail = 0x76,
    Heros_medal = 0x77,
    Balcony_shadow = 0x78,
    Save_point = 0x79,
    Prehistoric_villager_drummer = 0x7A,
    Prehistoric_villager_log_drummer = 0x7B,
    White_explosion_outline = 0x7C,
    Leenes_bell = 0x7D,
    Bat_hanging_upside_down = 0x7E,
    Computer_screen = 0x7F,
    Water_splash = 0x80,
    Explosion = 0x81,
    Robo_power_up_sparks = 0x82,
    Leaves_falling = 0x83,
    coins_spinning = 0x84,
    Hole_in_the_ground = 0x85,
    Cooking_smoke = 0x86,
    Small_explosion_clouds = 0x87,
    Wind_element_spinning = 0x88,
    Water_element = 0x89,
    Dirt_mound = 0x8A,
    Masamune_Spinning = 0x8B,
    Music_note = 0x8C,
    Small_fish = 0x8D,
    //Water_splash = 0x8E,
    //Lightning_bolt = 0x8F,
    //UNUSED = 0x90,
    //UNUSED = 0x91,
    Small_rock = 0x92,
    Rainbow_shell = 0x95,
    Shadow_beds = 0x96,
    Closed_portal = 0x97,
    Balloon = 0x98,
    Light_green_bush = 0x99,
    Shadow_on_the_ground = 0x9A,
    Brown_dreamstone = 0x9B,
    Crane_machine = 0x9C,
    //UNUSED = 0x9D,
    Dripping_water = 0x9E,
    Cupboard_doors = 0x9F,
    Brown_stones = 0xA0,
    Dark_green_bush = 0xA1,
    Journal = 0xA2,
    Norstein_Bekkler = 0xA3,
    Rat = 0xA4,
    Sparks_from_guillotine_blade = 0xA5,
    Zeal_teleporter = 0xA6,
    Ocean_palace_teleporter = 0xA7,
    Truce_Dome_director = 0xA8,
    Epoch_seats = 0xA9,
    Robot = 0xAA,
    Red_star = 0xAB,
    Sealed_portal = 0xAC,
    Animated_Zz_sleeping_icon = 0xAD,
    Flying_map_Epoch = 0xAE,
    Gray_cat = 0xAF,
    Yellow_cat = 0xB0,
    Alfador = 0xB1,
    Time_egg = 0xB2,
    Zeal_citizen_man_cast_ending = 0xB3,
    //Zeal_citizen_woman = 0xB4,
    Potted_plant = 0xB5,
    Kid_with_purple_hair_Glenn_Cyrus_cutscene = 0xB6,
    Sealed_chest = 0xB7,
    Squirrel_Programmers_Ending = 0xB8,
    Blue_poyozo = 0xB9,
    Stone_rubble_pile = 0xBA,
    Rusted_Robo = 0xBB,
    Gaspar_Gurus_cutscene = 0xBC,
    //UNUSED = 0xBD,
    Orange_cat = 0xBE,
    //Middle_Ages_or_Present_Age_villager_little_boy = 0xBF,
    //Middle_Ages_or_Present_Age_villager_little_girl = 0xC0,
    Spinning_water_element = 0xC1,
    Blue_shining_star_small = 0xC2,
    Blue_shining_star_large = 0xC3,
    Multiple_balloons = 0xC4,
    Dancing_woman_Millennial_Fair_ending = 0xC5,
    //Millennial_Fair_visitor_little_girl = 0xC6,
    Silver_Leenes_bell = 0xC7,
    Figure_atop_Magus_Castle = 0xC8,
    Serving_tray_with_drinks = 0xC9,
    THE_END_text = 0xCA,
    Human_Glenn = 0xCB,
    Queen_Zeal_Death_Peak = 0xCC,
    Schala_Death_Peak = 0xCD,
    Lavos_Death_Peak = 0xCE,
    Crono_Death_Peak = 0xCF,
    Hironobu_Sakaguchi = 0xD0,
    Yuji_Horii = 0xD1,
    Akira_Toriyama = 0xD2,
    Kazuhiko_Aoki = 0xD3,
    Lightning_flash = 0xD4,
    Lara = 0xD5,
    Purple_explosion = 0xD6,
    Cronos_mom_Millennial_Fair = 0xD7,
    //UNUSED = 0xD8,
    //UNUSED = 0xD9,
    //UNUSED = 0xDA,
    //UNUSED = 0xDB,
    //UNUSED = 0xDC,
    //UNUSED = 0xDD,
    //UNUSED = 0xDE,
    //UNUSED = 0xDF,
    Green_balloon = 0xE0,
    Yellow_balloon = 0xE1,
    Blue_balloon = 0xE2,
    Pink_balloon = 0xE3,
    Brown_glowing_light = 0xE4,
    Yellow_glowing_light = 0xE5,
    Purple_glowing_light = 0xE6,
    Blue_glowing_light = 0xE7,
    //UNUSED = 0xE8,
    //UNUSED = 0xE9,
    //UNUSED = 0xEA,
    //UNUSED = 0xEB,
    //UNUSED = 0xEC,
    //UNUSED = 0xED,
    //UNUSED = 0xEE,
    //UNUSED = 0xEF,
    //UNUSED = 0xF0,
    //UNUSED = 0xF1,
    //UNUSED = 0xF2,
    //UNUSED = 0xF3,
    //UNUSED = 0xF4,
    //UNUSED = 0xF5,
    //UNUSED = 0xF6,
    //UNUSED = 0xF7,
    //UNUSED = 0xF8,
    //UNUSED = 0xF9,
    //UNUSED = 0xFA,
    //UNUSED = 0xFB,
    //UNUSED = 0xFC,
    //UNUSED = 0xFD,
    //UNUSED = 0xFE,
    //UNUSED = 0xFF,
}

public enum MonsterType
{
    Nu = 000,
    Terrasaur = 002,
    Krawlie = 004,
    Hench = 005,
    Omicrone = 006,
    Martello = 007,
    BellBird = 008,
    Panel = 009,
    MammonMachine = 010,
    NONAME = 011,
    GreenImp = 013,
    StoneImp = 014,
    MudImp = 015,
    Roly = 016,
    Poly = 017,
    Rolypoly = 018,
    RolyRider = 019,
    LavosSupportMonster20 = 020,
    BlueEaglet = 021,
    GoldEaglet = 022,
    RedEaglet = 023,
    LavosSupportMonster24 = 024,
    AvianChaos = 025,
    ImpAce = 026,
    BantamImp = 027,
    Gnasher = 028,
    Gnawer = 029,
    NagaEtte = 030,
    LavosSupportMonster31 = 031,
    Ruminator = 032,
    LavosSupportMonster33 = 033,
    Octopod = 034,
    Octoblush = 035,
    Octobino = 036,
    QueenZeal = 037,
    FlyTrap = 038,
    MeatEater = 039,
    ManEater = 040,
    Krakker = 041,
    Egder = 042,
    Defunct = 043,
    Departed = 044,
    Deceased = 045,
    Decedent = 046,
    Macabre = 047,
    Reaper = 048,
    Guard1000AD = 049,
    Sentry = 050,
    FreeLancer = 051,
    Outlaw = 052,
    GigaMutant = 053,
    GigaMutant_BottomHalf = 054,
    TerraMutant = 055,
    TerraMutant_BottomHalf = 056,
    Juggler = 057,
    Retinite = 058,
    Mage = 059,
    LavosSupportMonster60 = 060,
    Reptite_Purple = 061,
    BlueShield = 062,
    YoduDe = 063,
    Incognito = 064,
    PeepingDoom = 065,
    Sidekick = 065,
    BossOrb = 066,
    JinnBottle = 069,
    EvilWeevil = 070,
    Tempurite = 071,
    Diablos = 072,
    Gargoyle = 073,
    Grimalkin = 074,
    //Hench = 075,
    Tpole = 076,
    Croaker = 077,
    Amphibite = 078,
    Bullfrog = 078,
    Rainfrog = 078,
    MadBat = 080,
    Vamp = 081,
    Scouter = 082,
    Flyclops = 083,
    Bugger = 084,
    Debugger = 085,
    Debuggest = 085,
    Sorceror = 086,
    Jinn = 087,
    Barghest = 088,
    LavosSupportMonster90 = 090,
    Crater = 091,
    Volcano = 092,
    Shitake = 093,
    Hetake = 094,
    Rubble = 095,
    LavosSupportMonster96 = 096,
    Shist = 097,
    Pahoehoe = 098,
    Nereid = 099,
    FakeSavePoint = 100,
    Mohaver = 101,
    Shadow = 102,
    LavosSupportMonster103 = 103,
    Base = 104,
    Acid = 105,
    Alkaline = 106,
    Ion = 107,
    Anion = 108,
    Thrasher = 109,
    LavosSpawn_Eye = 110,
    LavosSpawn_Shell = 111,
    Lasher = 112,
    Goblin = 113,
    Ogre = 114,
    CaveBat = 115,
    Ogan = 116,
    Flunky = 117,
    Groupie = 118,
    LavosSupportMonster119 = 119,
    LavosSupportMonster120 = 120,
    WingedApe = 121,
    CaveApe = 122,
    Megasaur = 123,
    Omnicrone = 124,
    Beast = 125,
    BlueBeast = 126,
    RedBeast = 126,
    Turret = 128,
    Lizardactyl = 129,
    FakeNu = 130,
    AvianRex = 131,
    Blob = 132,
    Gremlin = 134,
    Rat = 134,
    Runner = 136,
    Proto2 = 137,
    Proto3 = 138,
    Proto4 = 139,
    Bug = 140,
    Beetle = 141,
    Goon = 142,
    Cyrus = 143,
    Yakra = 144,
    Gato = 146,
    DragonTank = 147,
    DragonTankWheel = 148,
    Golem = 149,
    Synchrite = 150,
    Masa = 151,
    Mune = 152,
    Masamune = 153,
    Azala = 154,
    Nizbel = 155,
    NizbelII = 156,
    Slash_unarmed = 157,
    Slash_armed = 158,
    Flea = 159,
    FleaPlus = 160,
    Dalton = 161,
    DaltonPlus = 162,
    Mutant = 163,
    MetalMute = 164,
    SuperSlash = 165,
    Ozzie = 166,
    Ozzie2 = 167,
    GreatOzzie = 168,
    Heckran = 169,
    Gigasaur = 170,
    Leaper = 171,
    FossilApe = 172,
    DragonTankHead = 173,
    FrogKing = 174,
    Octorider = 175,
    Zeal = 176,
    ZealHand_Left = 177,
    ZealHand_Right = 178,
    Zombor_LowerHalf = 179,
    Zombor_UpperHalf = 180,
    Zombor_SandMonster_LowerHalf = 181,
    Zombor_SandMonster_UpperHalf = 182,
    Display = 183,
    MegaMutant = 184,
    MegaMutant_BottomHalf = 185,
    //SuperSlash = 186,
    //FleaPlus = 187,
    BlackTyrano = 188,
    RustTyrano = 189,
    Motherbrain = 190,
    Motherbrain_Body = 191,
    AtroposXR = 192,
    Cybot = 193,
    Lavos1 = 194,
    Lavos2 = 195,
    Lavos3 = 196,
    Lavos4 = 197,
    Lavos5 = 198,
    YakraXIII = 199,
    Tubster = 200,
    Lavos6 = 201,
    Lavos7 = 202,
    Lavos_SecondForm_MainBody = 203,
    Lavos_SecondForm_Arm1 = 204,
    Lavos_SecondForm_Arm2 = 205,
    LavosCore_MainBody = 206,
    Bit = 207,
    Byte = 208,
    GigaGaia = 209,
    GigaGaia_Arm1 = 210,
    GigaGaia_Arm2 = 211,
    Guardian = 212,
    Red_Scout = 213,
    Blue_Scout = 214,
    //LavosSpawn_Shell = 215,
    //LavosSpawn_Eye = 216,
    LaserGuard = 217,
    Lavos_Support_Monster218 = 218,
    Lavos_Support_Monster219 = 219,
    Lavos_Support_Monster221 = 221,
    Lavos_Support_Monster222 = 222,
    Lavos_Support_Monster223 = 223,
    Spekkio_Frog = 224,
    Spekkio_Kilwala = 225,
    Spekkio_Blue_Goblin = 226,
    Spekkio_Omnicrone = 227,
    Spekkio_Blue_Masamune = 228,
    Spekkio_Pink_Nu = 229,
    Lavos = 230,
    //Lavos = 231,
    //Lavos = 232,
    //Lavos = 233,
    //Lavos = 234,
    //Alien = 235,
    //Lavos = 235,
    //Lavos = 236,
    Lavos_Bit1 = 237,
    Hexapod = 238,
    Lavos_Bit2 = 239,
    //Flea? = 240,
    Unknown = 241,
    RolyBomber = 242,
    GolemBoss = 243,
    Johnny = 244,
    Basher = 245,
    BossOrb2 = 246,
    SonofSunFlame = 247,
    RSeries = 248,
    Magus = 249,
    Magus2 = 250,
    Magus3 = 251,
    Crono = 252,
    //Crono (Glitched) = 253,
    //Crono (Glitched) = 254,
    //Crono = 255,
}