//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FF.Rando.Companion.Games.FreeEnterprise {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FreeEnterprise {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FreeEnterprise() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FF.Rando.Companion.Games.FreeEnterprise.FreeEnterprise", typeof(FreeEnterprise).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_10DKCecil_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_10DKCecil_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_10DKCecil_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_10DKCecil_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_11Guards_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_11Guards_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_11Guards_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_11Guards_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_12Yang_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_12Yang_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_12Yang_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_12Yang_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_13Baigan_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_13Baigan_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_13Baigan_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_13Baigan_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_14Kainazzo_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_14Kainazzo_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_14Kainazzo_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_14Kainazzo_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_15DElf_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_15DElf_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_15DElf_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_15DElf_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_16MagusSis_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_16MagusSis_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_16MagusSis_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_16MagusSis_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_17Valvalis_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_17Valvalis_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_17Valvalis_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_17Valvalis_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_18Calcabrina_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_18Calcabrina_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_18Calcabrina_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_18Calcabrina_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_19Golbez_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_19Golbez_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_19Golbez_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_19Golbez_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_1MistD_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_1MistD_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_1MistD_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_1MistD_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_20Lugae_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_20Lugae_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_20Lugae_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_20Lugae_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_21Eblan_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_21Eblan_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_21Eblan_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_21Eblan_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_22Rubicante_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_22Rubicante_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_22Rubicante_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_22Rubicante_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_23EvilWall_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_23EvilWall_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_23EvilWall_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_23EvilWall_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_24Fiends_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_24Fiends_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_24Fiends_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_24Fiends_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_25CPU_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_25CPU_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_25CPU_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_25CPU_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_26Odin_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_26Odin_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_26Odin_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_26Odin_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_27Asura_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_27Asura_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_27Asura_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_27Asura_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_28Leviath_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_28Leviath_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_28Leviath_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_28Leviath_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_29Bahamut_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_29Bahamut_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_29Bahamut_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_29Bahamut_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_2Soldier_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_2Soldier_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_2Soldier_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_2Soldier_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_30PaleDim_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_30PaleDim_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_30PaleDim_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_30PaleDim_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_31LunarD_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_31LunarD_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_31LunarD_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_31LunarD_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_32Plague_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_32Plague_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_32Plague_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_32Plague_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_33Ogopogo_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_33Ogopogo_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_33Ogopogo_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_33Ogopogo_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_34Wyvern_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_34Wyvern_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_34Wyvern_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_34Wyvern_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_35DarkImps_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_35DarkImps_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_35DarkImps_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_35DarkImps_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_36Zeromus_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_36Zeromus_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_36Zeromus_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_36Zeromus_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_3Octo_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_3Octo_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_3Octo_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_3Octo_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_4Antlion_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_4Antlion_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_4Antlion_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_4Antlion_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_5WHag_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_5WHag_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_5WHag_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_5WHag_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_6Mombomb_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_6Mombomb_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_6Mombomb_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_6Mombomb_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_7Gauntlet_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_7Gauntlet_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_7Gauntlet_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_7Gauntlet_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_8Milon_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_8Milon_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_8Milon_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_8Milon_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_9MilonZ_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_9MilonZ_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Bosses_9MilonZ_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Bosses_9MilonZ_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_10MagmaKey_Check {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_10MagmaKey_Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_10MagmaKey_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_10MagmaKey_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_10MagmaKey_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_10MagmaKey_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_11TowerKey_Check {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_11TowerKey_Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_11TowerKey_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_11TowerKey_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_11TowerKey_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_11TowerKey_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_12LucaKey_Check {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_12LucaKey_Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_12LucaKey_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_12LucaKey_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_12LucaKey_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_12LucaKey_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_13Adamant_Check {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_13Adamant_Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_13Adamant_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_13Adamant_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_13Adamant_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_13Adamant_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_14LegendSword_Check {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_14LegendSword_Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_14LegendSword_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_14LegendSword_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_14LegendSword_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_14LegendSword_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_15Pan_Check {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_15Pan_Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_15Pan_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_15Pan_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_15Pan_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_15Pan_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_16Spoon_Check {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_16Spoon_Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_16Spoon_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_16Spoon_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_16Spoon_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_16Spoon_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_17RatTail_Check {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_17RatTail_Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_17RatTail_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_17RatTail_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_17RatTail_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_17RatTail_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_18PinkTail_Check {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_18PinkTail_Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_18PinkTail_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_18PinkTail_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_18PinkTail_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_18PinkTail_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_1THECrystal_Check {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_1THECrystal_Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_1THECrystal_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_1THECrystal_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_1THECrystal_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_1THECrystal_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_2Pass_Check {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_2Pass_Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_2Pass_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_2Pass_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_2Pass_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_2Pass_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_3Hook_Check {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_3Hook_Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_3Hook_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_3Hook_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_3Hook_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_3Hook_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_4DarkCrystal_Check {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_4DarkCrystal_Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_4DarkCrystal_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_4DarkCrystal_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_4DarkCrystal_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_4DarkCrystal_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_5EarthCrystal_Check {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_5EarthCrystal_Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_5EarthCrystal_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_5EarthCrystal_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_5EarthCrystal_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_5EarthCrystal_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_6TwinHarp_Check {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_6TwinHarp_Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_6TwinHarp_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_6TwinHarp_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_6TwinHarp_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_6TwinHarp_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_7Package_Check {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_7Package_Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_7Package_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_7Package_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_7Package_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_7Package_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_8SandRuby_Check {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_8SandRuby_Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_8SandRuby_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_8SandRuby_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_8SandRuby_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_8SandRuby_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_9BaronKey_Check {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_9BaronKey_Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_9BaronKey_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_9BaronKey_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_9BaronKey_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_9BaronKey_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SMB3_item_Anchor {
            get {
                object obj = ResourceManager.GetObject("SMB3_item_Anchor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
