//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizHawk.FreeEnterprise.Companion.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BizHawk.FreeEnterprise.Companion.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_10MagmaKey_Check {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_10MagmaKey_Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_10MagmaKey_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_10MagmaKey_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_10MagmaKey_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_10MagmaKey_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_11TowerKey_Check {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_11TowerKey_Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_11TowerKey_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_11TowerKey_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_11TowerKey_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_11TowerKey_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_12LucaKey_Check {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_12LucaKey_Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_12LucaKey_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_12LucaKey_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_12LucaKey_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_12LucaKey_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_13Adamant_Check {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_13Adamant_Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_13Adamant_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_13Adamant_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_13Adamant_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_13Adamant_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_14LegendSword_Check {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_14LegendSword_Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_14LegendSword_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_14LegendSword_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_14LegendSword_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_14LegendSword_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_15Pan_Check {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_15Pan_Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_15Pan_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_15Pan_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_15Pan_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_15Pan_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_16Spoon_Check {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_16Spoon_Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_16Spoon_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_16Spoon_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_16Spoon_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_16Spoon_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_17RatTail_Check {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_17RatTail_Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_17RatTail_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_17RatTail_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_17RatTail_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_17RatTail_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_18PinkTail_Check {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_18PinkTail_Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_18PinkTail_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_18PinkTail_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_18PinkTail_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_18PinkTail_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_1THECrystal_Check {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_1THECrystal_Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_1THECrystal_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_1THECrystal_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_1THECrystal_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_1THECrystal_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_2Pass_Check {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_2Pass_Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_2Pass_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_2Pass_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_2Pass_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_2Pass_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_3Hook_Check {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_3Hook_Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_3Hook_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_3Hook_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_3Hook_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_3Hook_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_4DarkCrystal_Check {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_4DarkCrystal_Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_4DarkCrystal_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_4DarkCrystal_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_4DarkCrystal_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_4DarkCrystal_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_5EarthCrystal_Check {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_5EarthCrystal_Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_5EarthCrystal_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_5EarthCrystal_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_5EarthCrystal_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_5EarthCrystal_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_6TwinHarp_Check {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_6TwinHarp_Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_6TwinHarp_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_6TwinHarp_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_6TwinHarp_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_6TwinHarp_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_7Package_Check {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_7Package_Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_7Package_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_7Package_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_7Package_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_7Package_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_8SandRuby_Check {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_8SandRuby_Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_8SandRuby_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_8SandRuby_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_8SandRuby_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_8SandRuby_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_9BaronKey_Check {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_9BaronKey_Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_9BaronKey_Color {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_9BaronKey_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFIVFE_Icons_9BaronKey_Gray {
            get {
                object obj = ResourceManager.GetObject("FFIVFE_Icons_9BaronKey_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Names {
            get {
                object obj = ResourceManager.GetObject("Names", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
